 
create table account (
    id bigint generated by default as identity,
    username varchar(100) not null,
    password varchar(255) not null,
    role varchar(255) not null,
    primary key (id)
);

create table job (
    job_id bigint generated by default as identity,
    media_id bigint,
    user_id bigint,
    company varchar(255) not null,
    img_url TEXT,
    job_url TEXT,
    title varchar(255) not null,
    status enum ('ACCEPTED','PENDING','REJECTED'),
    primary key (job_id)
);


create table social_media (
    media_id bigint generated by default as identity,
    homepage_url TEXT,
    instagram_url TEXT,
    twitter_url TEXT,
    primary key (media_id)
);

alter table if exists job add constraint FKl3axuuylg9sevj9c4xbd67hu7 foreign key (media_id) references social_media;
alter table if exists job add constraint FK8ccmokluykee90fief5pk0ub4 foreign key (user_id) references account;
